const CLUSTERS={
  'Events & Weddings':'#f4cfc5','Food & Desserts':'#f5d5b8','Products & Brands':'#d9e3d4',
  'Farm & Animals':'#cbd8bc','Travel & Stay':'#c9ddd9','Sales & Distribution':'#efc9a7'
};
const seedBusinesses=[
 ['charcuterie','Charcuterie To-go Stand',['Food & Desserts','Events & Weddings'],'To-go-Stand, an dem Gäste frisch belegte Boards aus verschiedenen Zutaten selbst zusammenstellen.'],
 ['chocolate','Schokolade Bars / Balls / Donuts',['Food & Desserts'],'Dekorierte Schokoladenprodukte mit Früchten, Nüssen, Toppings und saisonalen Varianten.'],
 ['eventplanning','Eventplanning',['Events & Weddings'],'Planung, Koordination und Durchführung von Hochzeiten und anderen Events.'],
 ['eventdeko','Eventdeko-Verleih',['Events & Weddings'],'Deko, Teller, Gläser, Tischwäsche und weitere Ausstattung für Veranstaltungen.'],
 ['eis','Eis mit echten Früchten',['Food & Desserts'],'Eis und Frozen Desserts mit echten Früchten und variablen Kombinationen.'],
 ['location','Hochzeitslocation',['Events & Weddings'],'Eigene Location für Hochzeiten und weitere Veranstaltungen.'],
 ['grazer','Ziegen-/Schafverleih',['Farm & Animals'],'Natürliche Landschaftspflege durch zeitweises Beweiden von Flächen.'],
 ['batchies','Batchies',['Products & Brands'],'Die bereits entworfene konkrete Geschenkbox-Idee/Marke mit eigenen Boxen und Produkten.'],
 ['matchies','Matchies',['Products & Brands','Events & Weddings'],'Personalisierte oder zusammenpassende Produkte wie Kleidung und Glasbecher, z. B. über Etsy/Printify.'],
 ['journals','Journals & Planer',['Products & Brands'],'Eigene Journals und Planer, digital und/oder physisch.'],
 ['farm','Gnadenhof',['Farm & Animals','Travel & Stay'],'Tierauffangstation mit Besuchern, Patenschaften, Erlebnissen und weiteren Angeboten.'],
 ['airbnb','Airbnb',['Travel & Stay'],'Ferienunterkünfte bzw. besondere Übernachtungsmöglichkeiten.'],
 ['pancake','Pancake Boxes / Store',['Food & Desserts'],'Pancakes mit Toppings, Früchten und Saucen als Box oder Store-Konzept.'],
 ['dessertbox','Dessert Boxes',['Food & Desserts'],'Gemischte Dessertboxen als eigenständiges Angebot.'],
 ['cakebox','Cake Boxes',['Food & Desserts'],'Boxen mit Kuchenstücken oder Mini-Cakes.'],
 ['cheesecake','Cheesecake on a Stick',['Food & Desserts'],'Cheesecake-Stücke am Stiel mit Schokolade, Toppings und Dekoration.'],
 ['cakepops','Cake Pops',['Food & Desserts','Events & Weddings'],'Dekorierte Cake Pops, auch passend zu Eventfarben und Themen.'],
 ['cookies','Cookies',['Food & Desserts','Events & Weddings'],'Dekorierte oder personalisierte Cookies für Einzelverkauf und Events.'],
 ['minis','Mini-Cookies & Mini-Brownies mit Dips',['Food & Desserts'],'Kleine Cookies und Brownies mit verschiedenen Dips als Sharing-Konzept.'],
 ['automaten','(Snack-)Automaten',['Sales & Distribution'],'24/7-Verkauf von Snacks, Getränken und ausgewählten eigenen Produkten.']
].map(([id,name,clusters,description])=>({id,name,clusters,description,status:'Idee',confirmed:true,notes:'',images:[]}));
const seedConnections=[
 ['eventplanning','location','Kundenfluss','Eventplanung kann die eigene Hochzeitslocation direkt anbieten.'],
 ['eventplanning','eventdeko','Cross-Selling','Dekoration und Ausstattung können direkt mitgeplant werden.'],
 ['eventplanning','charcuterie','Cross-Selling','Food-Angebote können als Eventbaustein vermittelt werden.'],
 ['eventplanning','dessertbox','Cross-Selling','Dessertangebote können direkt in Eventpakete integriert werden.'],
 ['eventplanning','matchies','Cross-Selling','Personalisierte Eventprodukte können passend angeboten werden.'],
 ['location','airbnb','Kundenfluss','Hochzeits- und Eventgäste können Übernachtungen buchen.'],
 ['location','eventdeko','Ressourcen','Location und Deko lassen sich als Paket kombinieren.'],
 ['location','cakepops','Cross-Selling','Desserts können passend zur Veranstaltung angeboten werden.'],
 ['location','cookies','Cross-Selling','Personalisierte Cookies können als Eventprodukt eingesetzt werden.'],
 ['farm','airbnb','Kundenfluss','Gnadenhof-Besucher können Übernachtungen buchen.'],
 ['farm','grazer','Ressourcen','Tiere des Gnadenhofs können für Landschaftspflege eingesetzt werden.'],
 ['farm','automaten','Standort','Automaten können Besucher am Hof versorgen.'],
 ['airbnb','automaten','Standort','Automaten können als 24/7-Angebot an Unterkünften stehen.'],
 ['airbnb','charcuterie','Cross-Selling','Charcuterie kann als Welcome- oder Aufenthaltsangebot angeboten werden.'],
 ['pancake','eis','Produkt','Eis kann als Topping oder Dessert ergänzt werden.'],
 ['pancake','chocolate','Produkt','Schokolade kann als Topping und Zusatzprodukt dienen.'],
 ['dessertbox','cakepops','Produkt','Cake Pops können Bestandteil eigener Dessertboxen sein.'],
 ['dessertbox','cookies','Produkt','Cookies können Bestandteil eigener Dessertboxen sein.'],
 ['dessertbox','cheesecake','Produkt','Cheesecake kann Bestandteil eigener Dessertboxen sein.'],
 ['dessertbox','minis','Produkt','Mini-Cookies und Brownies können Bestandteil eigener Dessertboxen sein.'],
 ['automaten','cookies','Vertrieb','Ausgewählte Cookies können über Automaten verkauft werden.'],
 ['automaten','minis','Vertrieb','Geeignete Snackvarianten können über Automaten verkauft werden.'],
 ['matchies','eventplanning','Kundenfluss','Eventkundschaft kann personalisierte Produkte entdecken.'],
 ['journals','eventplanning','Produkt','Event- und Hochzeitsplaner können zur Zielgruppe passen.'],
 ['batchies','matchies','Marketing','Beide Marken können bei passenden Zielgruppen gegenseitig sichtbar gemacht werden, ohne Batchies als generische Sammelbox umzudeuten.']
].map((x,i)=>({id:'c'+(i+1),from:x[0],to:x[1],type:x[2],description:x[3],confirmed:true}));
const seedCandidates=[{id:'cand1',name:'Charcuterie Boxen für Events',description:'Vorbereitete bzw. individuell zusammengestellte Charcuterie-Boxen für Events.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings']}];
const defaultState={businesses:seedBusinesses,connections:seedConnections,candidates:seedCandidates,brainstorm:[],inspiration:[]};
let state=loadState();let currentPage='dashboard';
function loadState(){try{return JSON.parse(localStorage.getItem('businessEcoState'))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem('businessEcoState',JSON.stringify(state))}
const pages=[['dashboard','Dashboard'],['businesses','Businesses'],['mindmap','Master Mindmap'],['synergies','Synergien'],['candidates','Kandidaten'],['inspiration','Inspiration'],['brainstorm','Brainstorming'],['implementation','Umsetzung'],['backup','Backup']];
const nav=document.getElementById('nav');
pages.forEach(([id,label])=>{const b=document.createElement('button');b.className='nav-btn';b.textContent=label;b.onclick=()=>renderPage(id);b.dataset.page=id;nav.appendChild(b)});
function renderPage(id){currentPage=id;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const titles={dashboard:['Dashboard','Dein gesamtes Business-Netzwerk auf einen Blick.'],businesses:['Businesses','Bestätigte Masterliste und Steckbriefe.'],mindmap:['Master Mindmap','Interaktive Karte aller bestätigten Businesses und Verbindungen.'],synergies:['Synergien','Cross-Selling, Kundenfluss und gemeinsame Ressourcen.'],candidates:['Kandidaten','Neue Ideen bleiben getrennt, bis du sie bestätigst.'],inspiration:['Inspiration','Bilder und Moodboard-Ideen mit Freigabestatus.'],brainstorm:['Brainstorming','Lose Gedanken, bevor daraus Kandidaten werden.'],implementation:['Umsetzung','Von der Idee bis zum aktiven Business.'],backup:['Backup','Daten exportieren, importieren oder zurücksetzen.']};document.getElementById('pageTitle').textContent=titles[id][0];document.getElementById('pageSubtitle').textContent=titles[id][1];document.getElementById('content').innerHTML='';({dashboard,businesses,mindmap,synergies,candidates,inspiration,brainstorm,implementation,backup}[id])()}
function section(html){document.getElementById('content').innerHTML=`<div class="section">${html}</div>`}
function dashboard(){const topConnections=[...state.businesses].map(b=>({b,n:state.connections.filter(c=>c.from===b.id||c.to===b.id).length})).sort((a,b)=>b.n-a.n).slice(0,5);section(`<div class="grid cards-4"><div class="metric"><small>Bestätigte Businesses</small><strong>${state.businesses.length}</strong></div><div class="metric"><small>Kandidaten</small><strong>${state.candidates.length}</strong></div><div class="metric"><small>Verbindungen</small><strong>${state.connections.length}</strong></div><div class="metric"><small>Cluster</small><strong>${Object.keys(CLUSTERS).length}</strong></div></div><div class="grid" style="grid-template-columns:1.3fr .7fr;margin-top:16px"><div class="panel"><div class="row space"><h3>Ökosystem Vorschau</h3><button class="secondary" onclick="renderPage('mindmap')">Mindmap öffnen</button></div><div class="image-placeholder" style="aspect-ratio:2/1">Interaktive Master-Mindmap mit ${state.businesses.length} Businesses</div></div><div class="panel"><h3>Stärkste Knoten</h3><div class="list">${topConnections.map(x=>`<div class="list-item"><span>${x.b.name}</span><span class="pill">${x.n} Verbindungen</span></div>`).join('')}</div></div></div>`)}
function businesses(){section(`<div class="toolbar"><input id="bizSearch" placeholder="Business suchen…"><select id="clusterFilter"><option value="">Alle Cluster</option>${Object.keys(CLUSTERS).map(c=>`<option>${c}</option>`).join('')}</select></div><div id="bizGrid" class="grid business-grid"></div>`);const paint=()=>{const q=document.getElementById('bizSearch').value.toLowerCase(),f=document.getElementById('clusterFilter').value;document.getElementById('bizGrid').innerHTML=state.businesses.filter(b=>(!q||b.name.toLowerCase().includes(q)||b.description.toLowerCase().includes(q))&&(!f||b.clusters.includes(f))).map(b=>`<div class="card business-card" onclick="openBusiness('${b.id}')"><div class="row space"><strong>${b.name}</strong><span class="status">${b.status}</span></div><div class="tags">${b.clusters.map(c=>`<span class="tag">${c}</span>`).join('')}</div><p class="muted">${b.description}</p><small>${state.connections.filter(c=>c.from===b.id||c.to===b.id).length} Verbindungen</small></div>`).join('')};paint();document.getElementById('bizSearch').oninput=paint;document.getElementById('clusterFilter').onchange=paint}
function openBusiness(id){const b=state.businesses.find(x=>x.id===id);const con=state.connections.filter(c=>c.from===id||c.to===id);section(`<button class="secondary" onclick="renderPage('businesses')">← Zurück</button><div class="detail" style="margin-top:14px"><div class="panel"><div class="row space"><div><h2>${b.name}</h2><div class="tags">${b.clusters.map(c=>`<span class="tag">${c}</span>`).join('')}</div></div><button class="secondary" onclick="editBusiness('${id}')">Bearbeiten</button></div><p>${b.description}</p><div class="kv"><strong>Status</strong><span>${b.status}</span><strong>Bestätigt</strong><span>Ja</span><strong>Notizen</strong><span>${b.notes||'—'}</span></div></div><div class="panel"><h3>Direkte Verbindungen</h3><div class="connections">${con.length?con.map(c=>{const other=state.businesses.find(x=>x.id===(c.from===id?c.to:c.from));return `<div class="connection"><strong>${other?.name||'Unbekannt'}</strong><br><span class="pill">${c.type}</span><p class="muted">${c.description}</p></div>`}).join(''):'<div class="empty">Noch keine Verbindung</div>'}</div></div></div><div class="panel" style="margin-top:16px"><h3>Inspiration</h3><div class="image-placeholder">Noch keine freigegebenen Bilder gespeichert</div></div>`);document.getElementById('pageTitle').textContent=b.name;document.getElementById('pageSubtitle').textContent='Business-Steckbrief und Netzwerk.'}
function mindmap(){section(`<div class="toolbar"><select id="edgeFilter"><option value="">Alle Verbindungstypen</option>${[...new Set(state.connections.map(c=>c.type))].map(t=>`<option>${t}</option>`).join('')}</select><button class="secondary" id="fitBtn">Ansicht zurücksetzen</button></div><div class="mindmap-wrap"><div id="mindCanvas" class="mindmap-canvas"></div></div>`);drawMindmap();document.getElementById('edgeFilter').onchange=drawMindmap}
function drawMindmap(){const canvas=document.getElementById('mindCanvas');if(!canvas)return;canvas.innerHTML='';const center={x:640,y:390};const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','edge-layer');svg.setAttribute('width','1500');svg.setAttribute('height','950');canvas.appendChild(svg);const clusterNames=Object.keys(CLUSTERS);const positions={};clusterNames.forEach((cl,ci)=>{const items=state.businesses.filter(b=>b.clusters.includes(cl));const angleBase=(Math.PI*2/clusterNames.length)*ci-Math.PI/2;const hubX=center.x+Math.cos(angleBase)*320,hubY=center.y+Math.sin(angleBase)*260;const label=document.createElement('div');label.className='cluster-label';label.style.left=(hubX-50)+'px';label.style.top=(hubY-65)+'px';label.textContent=cl;canvas.appendChild(label);items.forEach((b,i)=>{const spread=(i-(items.length-1)/2)*0.22;const angle=angleBase+spread;const radius=430+Math.min(100,Math.abs(i-(items.length-1)/2)*18);const x=center.x+Math.cos(angle)*radius,y=center.y+Math.sin(angle)*radius;positions[b.id]={x,y};const n=document.createElement('div');n.className='node';n.style.left=x+'px';n.style.top=y+'px';n.style.background=CLUSTERS[b.clusters[0]]||'#fff';n.innerHTML=`<strong>${b.name}</strong><div class="muted" style="font-size:11px;margin-top:4px">${b.clusters[0]}</div>`;n.onclick=()=>openBusiness(b.id);canvas.appendChild(n)})});const c=document.createElement('div');c.className='node center';c.style.left=center.x+'px';c.style.top=center.y+'px';c.innerHTML='MASTER<br>MINDMAP<div class="muted" style="font-size:11px;margin-top:6px">Business Ecosystem</div>';canvas.appendChild(c);const filter=document.getElementById('edgeFilter')?.value||'';state.connections.filter(e=>!filter||e.type===filter).forEach(e=>{const a=positions[e.from],b=positions[e.to];if(!a||!b)return;const line=document.createElementNS('http://www.w3.org/2000/svg','path');const ax=a.x+90,ay=a.y+35,bx=b.x+90,by=b.y+35;const mx=(ax+bx)/2,my=(ay+by)/2-30;line.setAttribute('d',`M ${ax} ${ay} Q ${mx} ${my} ${bx} ${by}`);line.setAttribute('class','edge');svg.appendChild(line)})}
function synergies(){const types=[...new Set(state.connections.map(c=>c.type))];section(`<div class="grid" style="grid-template-columns:.7fr 1.3fr"><div class="panel"><h3>Verbindungstypen</h3>${types.map(t=>`<div class="list-item"><span>${t}</span><span class="pill">${state.connections.filter(c=>c.type===t).length}</span></div>`).join('')}</div><div class="panel"><h3>Alle bestätigten Synergien</h3><div class="list">${state.connections.map(c=>{const a=state.businesses.find(b=>b.id===c.from)?.name,b=state.businesses.find(b=>b.id===c.to)?.name;return `<div class="list-item"><div><strong>${a} → ${b}</strong><div><span class="pill">${c.type}</span></div><small class="muted">${c.description}</small></div></div>`}).join('')}</div></div></div>`)}
function candidates(){section(`<div class="grid business-grid">${state.candidates.length?state.candidates.map(c=>`<div class="card candidate"><div class="row space"><strong>${c.name}</strong><span class="pill">${c.status}</span></div><div class="tags">${(c.clusters||[]).map(x=>`<span class="tag">${x}</span>`).join('')}</div><p>${c.description}</p><div class="row"><button class="primary" onclick="approveCandidate('${c.id}')">Zur Masterliste</button><button class="danger" onclick="removeCandidate('${c.id}')">Verwerfen</button></div></div>`).join(''):'<div class="empty">Keine Kandidaten vorhanden.</div>'}</div>`)}
function approveCandidate(id){const c=state.candidates.find(x=>x.id===id);state.businesses.push({id:'biz'+Date.now(),name:c.name,description:c.description,clusters:c.clusters||[],status:'Idee',confirmed:true,notes:'',images:[]});state.candidates=state.candidates.filter(x=>x.id!==id);save();renderPage('candidates')}
function removeCandidate(id){state.candidates=state.candidates.filter(x=>x.id!==id);save();renderPage('candidates')}
function inspiration(){section(`<div class="panel"><div class="row space"><h3>Inspirationssammlung</h3><button class="secondary" onclick="addInspiration()">+ Inspiration</button></div>${state.inspiration.length?`<div class="grid business-grid">${state.inspiration.map(i=>`<div class="card"><div class="image-placeholder">${i.url?'Bild-Link gespeichert':'Moodboard'}</div><h4>${i.title}</h4><p class="muted">${i.business||'Allgemein'}</p><span class="pill">${i.status}</span></div>`).join('')}</div>`:'<div class="empty">Noch keine Bilder oder Moodboard-Ideen gespeichert.</div>'}</div>`)}
function brainstorm(){section(`<div class="panel"><div class="row space"><h3>Freies Brainstorming</h3><button class="secondary" onclick="addBrainstorm()">+ Gedanke</button></div><div class="list">${state.brainstorm.length?state.brainstorm.map(x=>`<div class="list-item"><div>${x.text}</div><button class="secondary" onclick="brainToCandidate('${x.id}')">→ Kandidat</button></div>`).join(''):'<div class="empty">Noch keine losen Gedanken gespeichert.</div>'}</div></div>`)}
function implementation(){const stages=['Idee','Recherche','Konzept','Businessplan','Test','Aufbau','Aktiv','Skalierung'];section(`<div class="grid business-grid">${stages.map(s=>`<div class="panel"><h3>${s}</h3>${state.businesses.filter(b=>b.status===s).map(b=>`<div class="list-item"><span>${b.name}</span><button class="secondary" onclick="advance('${b.id}')">Weiter</button></div>`).join('')||'<div class="muted">—</div>'}</div>`).join('')}</div>`)}
function advance(id){const stages=['Idee','Recherche','Konzept','Businessplan','Test','Aufbau','Aktiv','Skalierung'];const b=state.businesses.find(x=>x.id===id);const i=stages.indexOf(b.status);if(i<stages.length-1)b.status=stages[i+1];save();renderPage('implementation')}
function backup(){section(`<div class="grid" style="grid-template-columns:1fr 1fr"><div class="panel"><h3>Export</h3><p>Speichert alle Businesses, Verbindungen, Kandidaten, Inspirationen und Brainstorming-Daten.</p><button class="primary" onclick="exportData()">JSON exportieren</button></div><div class="panel"><h3>Import</h3><input type="file" id="importFile" accept="application/json"><button class="secondary" style="margin-top:10px" onclick="importData()">Importieren</button></div><div class="panel"><h3>Reset</h3><p>Setzt die PWA auf die mitgelieferten Startdaten zurück.</p><button class="danger" onclick="resetData()">Startdaten wiederherstellen</button></div></div>`)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='business-ecosystem-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const f=document.getElementById('importFile').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();renderPage('dashboard')}catch{alert('Ungültige JSON-Datei')}};r.readAsText(f)}
function resetData(){if(confirm('Wirklich auf Startdaten zurücksetzen?')){state=structuredClone(defaultState);save();renderPage('dashboard')}}
function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function addBusiness(){modal(`<h2>Neues bestätigtes Business</h2><div class="form-grid"><label>Name<input id="mName"></label><label>Status<select id="mStatus"><option>Idee</option><option>Recherche</option><option>Konzept</option></select></label><label class="wide">Beschreibung<textarea id="mDesc"></textarea></label><label class="wide">Cluster (mit Komma trennen)<input id="mClusters" placeholder="Food & Desserts, Events & Weddings"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveBusiness()">Speichern</button></div>`)}
function saveBusiness(){const name=mName.value.trim();if(!name)return;state.businesses.push({id:'biz'+Date.now(),name,description:mDesc.value.trim(),clusters:mClusters.value.split(',').map(x=>x.trim()).filter(Boolean),status:mStatus.value,confirmed:true,notes:'',images:[]});save();closeModal();renderPage('businesses')}
function editBusiness(id){const b=state.businesses.find(x=>x.id===id);modal(`<h2>${b.name} bearbeiten</h2><div class="form-grid"><label>Name<input id="eName" value="${esc(b.name)}"></label><label>Status<select id="eStatus">${['Idee','Recherche','Konzept','Businessplan','Test','Aufbau','Aktiv','Skalierung'].map(s=>`<option ${s===b.status?'selected':''}>${s}</option>`).join('')}</select></label><label class="wide">Beschreibung<textarea id="eDesc">${esc(b.description)}</textarea></label><label class="wide">Cluster<input id="eClusters" value="${esc(b.clusters.join(', '))}"></label><label class="wide">Notizen<textarea id="eNotes">${esc(b.notes||'')}</textarea></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveEdit('${id}')">Speichern</button></div>`)}
function saveEdit(id){const b=state.businesses.find(x=>x.id===id);b.name=eName.value;b.status=eStatus.value;b.description=eDesc.value;b.clusters=eClusters.value.split(',').map(x=>x.trim()).filter(Boolean);b.notes=eNotes.value;save();closeModal();openBusiness(id)}
function addCandidate(){modal(`<h2>Neuer Kandidat</h2><div class="form-grid"><label class="wide">Name<input id="cName"></label><label class="wide">Beschreibung<textarea id="cDesc"></textarea></label><label class="wide">Cluster<input id="cClusters"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveCandidate()">Speichern</button></div>`)}
function saveCandidate(){if(!cName.value.trim())return;state.candidates.push({id:'cand'+Date.now(),name:cName.value.trim(),description:cDesc.value.trim(),clusters:cClusters.value.split(',').map(x=>x.trim()).filter(Boolean),status:'Kandidat'});save();closeModal();renderPage('candidates')}
function addBrainstorm(){modal(`<h2>Brainstorming-Idee</h2><label>Gedanke<textarea id="bText"></textarea></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveBrainstorm()">Speichern</button></div>`)}
function saveBrainstorm(){if(!bText.value.trim())return;state.brainstorm.push({id:'brain'+Date.now(),text:bText.value.trim()});save();closeModal();renderPage('brainstorm')}
function brainToCandidate(id){const b=state.brainstorm.find(x=>x.id===id);state.candidates.push({id:'cand'+Date.now(),name:b.text.slice(0,60),description:b.text,clusters:[],status:'Kandidat'});state.brainstorm=state.brainstorm.filter(x=>x.id!==id);save();renderPage('brainstorm')}
function addInspiration(){modal(`<h2>Inspiration speichern</h2><div class="form-grid"><label>Titel<input id="iTitle"></label><label>Business<input id="iBusiness"></label><label class="wide">Bild-URL / Hinweis<input id="iUrl"></label><label>Status<select id="iStatus"><option>Nicht geprüft</option><option>Bestätigt</option><option>Abgelehnt</option></select></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveInspiration()">Speichern</button></div>`)}
function saveInspiration(){if(!iTitle.value.trim())return;state.inspiration.push({id:'img'+Date.now(),title:iTitle.value.trim(),business:iBusiness.value.trim(),url:iUrl.value.trim(),status:iStatus.value});save();closeModal();renderPage('inspiration')}
function esc(s){return (s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
document.getElementById('addBusinessBtn').onclick=addBusiness;document.getElementById('addCandidateBtn').onclick=addCandidate;document.getElementById('exportQuick').onclick=exportData;
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderPage('dashboard');
