const CLUSTERS={
  'Events & Weddings':'#f4cfc5','Food & Desserts':'#f5d5b8','Products & Brands':'#d9e3d4',
  'Farm & Animals':'#cbd8bc','Travel & Stay':'#c9ddd9','Sales & Distribution':'#efc9a7'
};
const seedBusinesses=[
 ['charcuterie','Charcuterie To-go Stand',['Food & Desserts','Events & Weddings'],'To-go-Stand, an dem Gäste frisch belegte Boards aus verschiedenen Zutaten selbst zusammenstellen.'],
 ['chocolate','Schokolade Bars / Balls / Donuts',['Food & Desserts'],'Dekorierte Schokoladenprodukte mit Früchten, Nüssen, Toppings und saisonalen Varianten.'],
 ['eventplanning','Eventplanning',['Events & Weddings'],'Planung, Koordination und Durchführung von Hochzeiten und anderen Events.'],
 ['eventdeko','Eventdeko-Verleih',['Events & Weddings'],'Deko, Teller, Gläser, Tischwäsche und weitere Ausstattung für Veranstaltungen.'],
 ['eis','Eis mit echten Früchten',['Food & Desserts'],'Eis und Frozen Desserts mit echten Früchten und variablen Kombinationen.'],
 ['location','Hochzeitslocation',['Events & Weddings'],'Eigene Location für Hochzeiten und weitere Veranstaltungen.'],
 ['grazer','Ziegen-/Schafverleih',['Farm & Animals'],'Natürliche Landschaftspflege durch zeitweises Beweiden von Flächen.'],
 ['batchies','Batchies',['Products & Brands'],'Die bereits entworfene konkrete Geschenkbox-Idee/Marke mit eigenen Boxen und Produkten.'],
 ['matchies','Matchies',['Products & Brands','Events & Weddings'],'Personalisierte oder zusammenpassende Produkte wie Kleidung und Glasbecher, z. B. über Etsy/Printify.'],
 ['journals','Journals & Planer',['Products & Brands'],'Eigene Journals und Planer, digital und/oder physisch.'],
 ['farm','Gnadenhof',['Farm & Animals','Travel & Stay'],'Tierauffangstation mit Besuchern, Patenschaften, Erlebnissen und weiteren Angeboten.'],
 ['airbnb','Airbnb',['Travel & Stay'],'Ferienunterkünfte bzw. besondere Übernachtungsmöglichkeiten.'],
 ['pancake','Pancake Boxes / Store',['Food & Desserts'],'Pancakes mit Toppings, Früchten und Saucen als Box oder Store-Konzept.'],
 ['dessertbox','Dessert Boxes',['Food & Desserts'],'Gemischte Dessertboxen als eigenständiges Angebot.'],
 ['cakebox','Cake Boxes',['Food & Desserts'],'Boxen mit Kuchenstücken oder Mini-Cakes.'],
 ['cheesecake','Cheesecake on a Stick',['Food & Desserts'],'Cheesecake-Stücke am Stiel mit Schokolade, Toppings und Dekoration.'],
 ['cakepops','Cake Pops',['Food & Desserts','Events & Weddings'],'Dekorierte Cake Pops, auch passend zu Eventfarben und Themen.'],
 ['cookies','Cookies',['Food & Desserts','Events & Weddings'],'Dekorierte oder personalisierte Cookies für Einzelverkauf und Events.'],
 ['minis','Mini-Cookies & Mini-Brownies mit Dips',['Food & Desserts'],'Kleine Cookies und Brownies mit verschiedenen Dips als Sharing-Konzept.'],
 ['hofladen','Hofladen',['Farm & Animals','Sales & Distribution','Travel & Stay'],'Eigener Hofladen am Gnadenhof/Hof mit eigenen und hofnahen Produkten – ausdrücklich z. B. eigenen Eiern – sowie passenden eigenen Angeboten.'],
 ['automaten','(Snack-)Automaten',['Sales & Distribution'],'24/7-Verkauf von Snacks, Getränken und ausgewählten eigenen Produkten.']
].map(([id,name,clusters,description])=>({id,name,clusters,description,status:'Idee',confirmed:true,notes:'',images:[]}));
const seedConnections=[
 ['eventplanning','location','Kundenfluss','Eventplanung kann die eigene Hochzeitslocation direkt anbieten.'],
 ['eventplanning','eventdeko','Cross-Selling','Dekoration und Ausstattung können direkt mitgeplant werden.'],
 ['eventplanning','charcuterie','Cross-Selling','Food-Angebote können als Eventbaustein vermittelt werden.'],
 ['eventplanning','dessertbox','Cross-Selling','Dessertangebote können direkt in Eventpakete integriert werden.'],
 ['eventplanning','matchies','Cross-Selling','Personalisierte Eventprodukte können passend angeboten werden.'],
 ['location','airbnb','Kundenfluss','Hochzeits- und Eventgäste können Übernachtungen buchen.'],
 ['location','eventdeko','Ressourcen','Location und Deko lassen sich als Paket kombinieren.'],
 ['location','cakepops','Cross-Selling','Desserts können passend zur Veranstaltung angeboten werden.'],
 ['location','cookies','Cross-Selling','Personalisierte Cookies können als Eventprodukt eingesetzt werden.'],
 ['farm','airbnb','Kundenfluss','Gnadenhof-Besucher können Übernachtungen buchen.'],
 ['farm','grazer','Ressourcen','Tiere des Gnadenhofs können für Landschaftspflege eingesetzt werden.'],
 ['farm','automaten','Standort','Automaten können Besucher am Hof versorgen.'],
 ['airbnb','automaten','Standort','Automaten können als 24/7-Angebot an Unterkünften stehen.'],
 ['airbnb','charcuterie','Cross-Selling','Charcuterie kann als Welcome- oder Aufenthaltsangebot angeboten werden.'],
 ['pancake','eis','Produkt','Eis kann als Topping oder Dessert ergänzt werden.'],
 ['pancake','chocolate','Produkt','Schokolade kann als Topping und Zusatzprodukt dienen.'],
 ['dessertbox','cakepops','Produkt','Cake Pops können Bestandteil eigener Dessertboxen sein.'],
 ['dessertbox','cookies','Produkt','Cookies können Bestandteil eigener Dessertboxen sein.'],
 ['dessertbox','cheesecake','Produkt','Cheesecake kann Bestandteil eigener Dessertboxen sein.'],
 ['dessertbox','minis','Produkt','Mini-Cookies und Brownies können Bestandteil eigener Dessertboxen sein.'],
 ['automaten','cookies','Vertrieb','Ausgewählte Cookies können über Automaten verkauft werden.'],
 ['automaten','minis','Vertrieb','Geeignete Snackvarianten können über Automaten verkauft werden.'],
 ['matchies','eventplanning','Kundenfluss','Eventkundschaft kann personalisierte Produkte entdecken.'],
 ['journals','eventplanning','Produkt','Event- und Hochzeitsplaner können zur Zielgruppe passen.'],
 ['batchies','matchies','Marketing','Beide Marken können bei passenden Zielgruppen gegenseitig sichtbar gemacht werden, ohne Batchies als generische Sammelbox umzudeuten.'],
 ['farm','hofladen','Produkt','Eigene und hofnahe Produkte des Hofs – ausdrücklich z. B. eigene Eier – können direkt im Hofladen verkauft werden.'],
 ['hofladen','airbnb','Cross-Selling','Airbnb-Gäste können im Hofladen einkaufen oder vorbereitete Hofprodukte für ihren Aufenthalt erhalten.'],
 ['hofladen','automaten','Vertrieb','Ein Teil des Hofladen-Sortiments kann außerhalb der Öffnungszeiten über Automaten verfügbar sein.'],
 ['hofladen','matchies','Vertrieb','Passendes Hof- oder Tier-Merchandise kann im Hofladen verkauft werden.'],
 ['hofladen','cookies','Vertrieb','Geeignete eigene Food-Produkte können je nach rechtlichen und hygienischen Voraussetzungen im Hofladen angeboten werden.']
].map((x,i)=>({id:'c'+(i+1),from:x[0],to:x[1],type:x[2],description:x[3],confirmed:true}));
const seedCandidates=[
 {id:'cand-char-event',name:'Charcuterie Boxen für Events',description:'Vorbereitete oder individuell zusammengestellte Charcuterie-Boxen für Hochzeiten, Firmenfeiern, Picknicks und andere Events.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Eventgäste, Brautpaare, Unternehmen',synergies:['Charcuterie To-go Stand','Eventplanning','Hochzeitslocation','Airbnb'],resources:'Küche/Kühlung, Verpackung, Zutaten wie beim Charcuterie-Stand',channels:'Eventverkauf, Vorbestellung, Abholung/Lieferung',effort:'Mittel'},
 {id:'cand-mobile-dessert',name:'Mobile Dessert-/Snack-Bar',description:'Mobiler Stand oder Wagen für Cheesecake on a Stick, Cake Pops, Cookies, Brownies, Schokolade oder Eis direkt auf Events.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Hochzeiten, Geburtstage, Firmen- und Hofevents',synergies:['Eventplanning','Hochzeitslocation','Eventdeko-Verleih','Cheesecake on a Stick','Cake Pops','Cookies'],resources:'Mobiler Stand, Kühlung, Ausgabe-Equipment',channels:'Events, Pop-ups, Hofveranstaltungen',effort:'Mittel'},
 {id:'cand-brunch-box',name:'Brunch-/Breakfast Boxes',description:'Frühstücks- oder Brunchboxen mit Pancakes, Obst, Backwaren, Aufstrichen und Getränken für Übernachtungen oder Events.',status:'Kandidat',clusters:['Food & Desserts','Travel & Stay'],target:'Airbnb-Gäste, Hochzeitsgesellschaften, Geburtstage',synergies:['Airbnb','Pancake Boxes / Store','Charcuterie To-go Stand','Dessert Boxes'],resources:'Küche, Kühlung, Boxverpackungen',channels:'Vorbestellung, Airbnb-Add-on, Events',effort:'Einfach–Mittel'},
 {id:'cand-picnic',name:'Picnic Setup / Picnic Experience',description:'Komplett vorbereitete Picknicks mit Decken, Kissen, Geschirr, Deko sowie optional Charcuterie und Desserts.',status:'Kandidat',clusters:['Events & Weddings','Travel & Stay','Food & Desserts'],target:'Paare, Freundesgruppen, JGAs, Airbnb-Gäste',synergies:['Eventdeko-Verleih','Charcuterie To-go Stand','Airbnb','Eventplanning'],resources:'Deko, Textilien, Geschirr, Transport',channels:'Buchung, Airbnb-Add-on, Events',effort:'Mittel'},
 {id:'cand-coffee-cart',name:'Mobile Coffee Bar / Coffee Cart',description:'Mobile Kaffee- und Heißgetränkestation für Hochzeiten, Events, Hof und Pop-ups; kombinierbar mit Desserts.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Eventgäste, Hofbesucher, Firmen',synergies:['Hochzeitslocation','Eventplanning','Cookies','Cake Pops','Gnadenhof'],resources:'Kaffeemaschine, Wasser/Strom, mobiler Tresen',channels:'Events, Hof, Pop-ups',effort:'Mittel'},
 {id:'cand-flower-bar',name:'Flower Bar / Build-your-own-Bouquet',description:'Gäste stellen sich aus vorbereiteten Blumen selbst kleine Sträuße oder florale Arrangements zusammen.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Hochzeiten, JGAs, Workshops, Hofbesucher',synergies:['Eventplanning','Hochzeitslocation','Eventdeko-Verleih','Airbnb'],resources:'Blumen, Kühlung/Wasser, Präsentationstische',channels:'Events, Workshops, Hofladen',effort:'Mittel'},
 {id:'cand-diy-stations',name:'DIY-Eventstationen',description:'Buchbare Kreativstationen, z. B. Perlenarmbänder, Kerzen, Blumenkränze, Schlüsselanhänger oder personalisierte Gläser.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'JGAs, Geburtstage, Hochzeiten, Firmen',synergies:['Eventplanning','Matchies','Hochzeitslocation','Airbnb'],resources:'Materialsets, Tische, Anleitung/Personal',channels:'Events, Workshops, Retreats',effort:'Einfach–Mittel'},
 {id:'cand-content',name:'Wedding Content Creation',description:'Smartphone-basierte Begleitung von Hochzeiten für Reels, Behind-the-scenes und schnelle Social-Media-Clips.',status:'Kandidat',clusters:['Events & Weddings'],target:'Brautpaare und Hochzeitsgesellschaften',synergies:['Eventplanning','Hochzeitslocation','Matchies'],resources:'Smartphone/Kamera, Schnittsoftware, Speicher',channels:'Direktbuchung, Eventpakete',effort:'Einfach–Mittel'},
 {id:'cand-photobooth',name:'Photobooth / Audio Guestbook Verleih',description:'Fotobox, Sofortbild-Setup, Audio- oder Videogästebuch als buchbares Event-Extra.',status:'Kandidat',clusters:['Events & Weddings'],target:'Hochzeiten, Geburtstage, Firmen',synergies:['Eventplanning','Hochzeitslocation','Eventdeko-Verleih'],resources:'Fotobox/Telefon/Kamera, Transport, Technik',channels:'Vermietung, Eventpakete',effort:'Mittel'},
 {id:'cand-furniture',name:'Event Furniture Rental',description:'Verleih von Loungemöbeln, Stehtischen, mobilen Bars, Bögen, Staffeleien und besonderen Eventmöbeln.',status:'Kandidat',clusters:['Events & Weddings'],target:'Hochzeiten, Firmen, Veranstalter',synergies:['Eventdeko-Verleih','Eventplanning','Hochzeitslocation'],resources:'Lager, Transporter, Reinigung/Instandhaltung',channels:'Vermietung, Komplettpakete',effort:'Aufwendig'},
 {id:'cand-mocktail',name:'Mobile Bar / Mocktail Bar',description:'Mobile Bar für alkoholfreie Cocktails, Limonaden und Signature Drinks mit echter Frucht und Eventdesign.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Hochzeiten, Firmen, Geburtstage',synergies:['Eis mit echten Früchten','Eventplanning','Hochzeitslocation','Eventdeko-Verleih'],resources:'Mobiler Tresen, Kühlung, Gläser, Eis',channels:'Events, Pop-ups',effort:'Mittel'},
 {id:'cand-lemonade',name:'Signature Lemonade / Fruit Drinks',description:'Eigene Limonaden, Eistees und Fruchtgetränke als Einzelprodukt oder Ergänzung anderer Food-Angebote.',status:'Kandidat',clusters:['Food & Desserts','Sales & Distribution'],target:'Eventgäste, Hofbesucher, To-go-Kundschaft',synergies:['Pancake Boxes / Store','Eis mit echten Früchten','Gnadenhof','(Snack-)Automaten'],resources:'Getränkezubereitung, Kühlung, Flaschen/Becher',channels:'Stores, Events, Automaten je nach Haltbarkeit',effort:'Einfach–Mittel'},
 {id:'cand-fruitcups',name:'Fruit Cups / Chocolate Fruit Cups',description:'Becher mit frischem Obst, optional Schokolade, Toppings oder Eis.',status:'Kandidat',clusters:['Food & Desserts'],target:'To-go-Kundschaft, Events, Hofbesucher',synergies:['Schokolade Bars / Balls / Donuts','Eis mit echten Früchten','Pancake Boxes / Store'],resources:'Kühlung, Obst, Becher, Toppings',channels:'Stand, Events, Store',effort:'Einfach'},
 {id:'cand-waffle-stick',name:'Waffle-on-a-stick / Mini-Waffle Bar',description:'Mini-Waffeln am Stiel oder als Bar-Konzept mit frei wählbaren Toppings und Dips.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Events, Familien, To-go-Kundschaft',synergies:['Pancake Boxes / Store','Schokolade Bars / Balls / Donuts','Eis mit echten Früchten','Mini-Cookies & Mini-Brownies mit Dips'],resources:'Waffeleisen, Teigstation, Toppings',channels:'Events, Pop-ups, Store',effort:'Einfach–Mittel'},
 {id:'cand-donut',name:'Mini Donut Bar',description:'Frische Mini-Donuts, die mit Glasuren und Toppings individuell dekoriert werden.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Events, Familien, Dessertkundschaft',synergies:['Schokolade Bars / Balls / Donuts','Dessert Boxes','Eventplanning'],resources:'Donutgerät/Fritteuse oder Backtechnik, Toppings',channels:'Events, Store, Boxen',effort:'Mittel'},
 {id:'cand-dessert-catering',name:'Dessert Catering / Dessert Table Service',description:'Kompletter Desserttisch inklusive Planung, Gestaltung, Aufbau und Befüllung mit bestehenden Süßwaren.',status:'Kandidat',clusters:['Food & Desserts','Events & Weddings'],target:'Hochzeiten, Geburtstage, Firmen',synergies:['Dessert Boxes','Cake Pops','Cookies','Cheesecake on a Stick','Eventdeko-Verleih','Eventplanning'],resources:'Transport, Präsentationsmöbel, Kühlung, Aufbau',channels:'Eventpakete, Direktbuchung',effort:'Mittel'},
 {id:'cand-favours',name:'Custom Wedding Favours / Gastgeschenke',description:'Personalisierte kleine Gastgeschenke oder Snacks passend zum Design einer Hochzeit oder Feier.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Brautpaare, Veranstalter',synergies:['Matchies','Cookies','Schokolade Bars / Balls / Donuts','Journals & Planer','Eventplanning'],resources:'Personalisierung, Verpackung, Lager',channels:'Etsy/Online, Eventplanung, Direktbestellung',effort:'Einfach–Mittel'},
 {id:'cand-airbnb-welcome',name:'Welcome Boxes für Airbnb',description:'Begrüßungsboxen für Übernachtungsgäste, z. B. mit Snacks, Hofprodukten oder kleinen Reiseextras; eigenständig und nicht automatisch Batchies.',status:'Kandidat',clusters:['Travel & Stay','Products & Brands'],target:'Airbnb-Gäste',synergies:['Airbnb','Hofladen','Cookies','Charcuterie To-go Stand'],resources:'Verpackung, Lager, saisonale Inhalte',channels:'Airbnb-Add-on, im Übernachtungspreis',effort:'Einfach'},
 {id:'cand-romantic-setup',name:'Romantic Setup im Airbnb',description:'Dekoration und kleine Extras für Jahrestag, Geburtstag, Proposal oder Honeymoon direkt in der Unterkunft.',status:'Kandidat',clusters:['Travel & Stay','Events & Weddings'],target:'Paare und besondere Anlässe',synergies:['Airbnb','Eventdeko-Verleih','Charcuterie To-go Stand','Dessert Boxes','Matchies'],resources:'Deko, Aufbauzeit, optionale Food-Produkte',channels:'Airbnb-Add-on',effort:'Einfach–Mittel'},
 {id:'cand-proposal',name:'Proposal Planning',description:'Planung und Aufbau von Heiratsanträgen inklusive Location, Deko, Picknick, Food und optional Content/Fotografie.',status:'Kandidat',clusters:['Events & Weddings','Travel & Stay'],target:'Paare mit geplantem Heiratsantrag',synergies:['Eventplanning','Eventdeko-Verleih','Picnic Setup / Picnic Experience','Airbnb','Hochzeitslocation'],resources:'Planung, Deko, Partnernetzwerk',channels:'Direktbuchung, Social Media',effort:'Mittel'},
 {id:'cand-jga',name:'JGA Planning / Bachelorette Packages',description:'Komplettpakete für Junggesellinnenabschiede mit Planung, Unterkunft, Aktivitäten, Food und personalisierten Produkten.',status:'Kandidat',clusters:['Events & Weddings','Travel & Stay','Products & Brands'],target:'JGA-Gruppen',synergies:['Eventplanning','Airbnb','Matchies','DIY-Eventstationen','Picnic Setup / Picnic Experience'],resources:'Planung, Partner/Activities, Unterkunft',channels:'Pakete, Onlinebuchung',effort:'Mittel'},
 {id:'cand-kids-farm',name:'Kindergeburtstage auf dem Hof',description:'Geburtstagsprogramme mit Tieren, kleinen Aktivitäten, Food und optional dekorierten Desserts.',status:'Kandidat',clusters:['Farm & Animals','Events & Weddings','Food & Desserts'],target:'Familien mit Kindern',synergies:['Gnadenhof','Cake Pops','Cookies','Eventdeko-Verleih','Hofladen'],resources:'Sicherer Besucherbereich, Betreuung, Sanitär/Schlechtwetterlösung',channels:'Direktbuchung, lokale Werbung',effort:'Mittel–Aufwendig'},
 {id:'cand-patenschaft-box',name:'Tierpatenschafts-Geschenkboxen',description:'Geschenkbare Tierpatenschaft mit Urkunde, Foto/Infos zum Tier und optional passenden kleinen Artikeln.',status:'Kandidat',clusters:['Farm & Animals','Products & Brands'],target:'Tierfreunde, Geschenkekäufer',synergies:['Gnadenhof','Matchies','Hofladen'],resources:'Patenschaftssystem, Druck/Verpackung',channels:'Online, Hofladen, Geschenkverkauf',effort:'Einfach–Mittel'},
 {id:'cand-farm-merch',name:'Tier-/Hof-Merchandise',description:'Shirts, Becher, Taschen, Kalender und weitere Produkte mit Motiven echter Tiere oder des Hofbrands.',status:'Kandidat',clusters:['Farm & Animals','Products & Brands'],target:'Gnadenhof-Besucher, Tierfreunde',synergies:['Gnadenhof','Matchies','Hofladen','Airbnb'],resources:'Designs, Print-on-Demand oder Lagerware',channels:'Hofladen, Etsy/Online, Events',effort:'Einfach–Mittel'},
 {id:'cand-selfservice-shop',name:'Self-Service Farm Shop',description:'Unbemannter bzw. teilautomatisierter 24/7-Hofverkauf über Schränke, Kühlschränke oder Bezahlsysteme.',status:'Kandidat',clusters:['Farm & Animals','Sales & Distribution'],target:'Anwohner, Ausflügler, Hofgäste',synergies:['Hofladen','(Snack-)Automaten','Gnadenhof','Airbnb'],resources:'Kühlung, Zugang, Bezahlsystem, Sicherheit',channels:'24/7 vor Ort',effort:'Mittel'},
 {id:'cand-pyo-flowers',name:'Pick-your-own Flowers / Blumenfeld',description:'Blumenfeld, auf dem Besucher selbst Blumen schneiden und bezahlen können.',status:'Kandidat',clusters:['Farm & Animals','Events & Weddings'],target:'Ausflügler, Hochzeiten, Airbnb-Gäste',synergies:['Flower Bar / Build-your-own-Bouquet','Hochzeitslocation','Gnadenhof','Airbnb'],resources:'Anbaufläche, Bewässerung, Bezahlsystem',channels:'Hof, Events, Selbstbedienung',effort:'Mittel'},
 {id:'cand-pumpkin',name:'Pumpkin Patch / saisonale Erlebnisfläche',description:'Saisonales Kürbisfeld mit Verkauf, Fotospots und ergänzenden Herbstangeboten.',status:'Kandidat',clusters:['Farm & Animals','Travel & Stay','Events & Weddings'],target:'Familien, Ausflügler, Fotografiekundschaft',synergies:['Gnadenhof','Hofladen','Airbnb','Cookies','Signature Lemonade / Fruit Drinks'],resources:'Fläche, Anbau, Besucherführung, Deko',channels:'Saisonbetrieb vor Ort',effort:'Mittel–Aufwendig'},
 {id:'cand-christmas-farm',name:'Christmas Farm / Weihnachtsmarkt auf dem Hof',description:'Saisonales Hofevent mit Tieren, Food, Heißgetränken, Geschenkprodukten und kleinen Verkaufsständen.',status:'Kandidat',clusters:['Farm & Animals','Events & Weddings','Sales & Distribution'],target:'Familien, Ausflügler, Geschenkekäufer',synergies:['Gnadenhof','Hofladen','Cookies','Schokolade Bars / Balls / Donuts','Matchies'],resources:'Eventfläche, Stände, Strom, Genehmigungen, Personal',channels:'Saisonveranstaltung',effort:'Aufwendig'},
 {id:'cand-workshops',name:'Workshops',description:'Buchbare Kurse wie Cookie Decorating, Cake Pops, Schokolade, Charcuterie, Journaling, Blumenkränze oder DIY.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands','Food & Desserts'],target:'Freundesgruppen, JGAs, Firmen, Airbnb-Gäste',synergies:['Cookies','Cake Pops','Schokolade Bars / Balls / Donuts','Journals & Planer','Airbnb','Hochzeitslocation'],resources:'Raum, Material, Anleitung/Personal',channels:'Direktbuchung, Events, Retreats',effort:'Einfach–Mittel'},
 {id:'cand-retreats',name:'Creative Retreats',description:'Mehrtagige Kreativaufenthalte mit Übernachtung, Workshops, Food und optional Tieren/Natur.',status:'Kandidat',clusters:['Travel & Stay','Products & Brands','Farm & Animals'],target:'Freundesgruppen, Kreative, kleine Teams',synergies:['Airbnb','Workshops','Gnadenhof','Journals & Planer','Food & Desserts'],resources:'Unterkunft, Workshopraum, Programmplanung',channels:'Paketbuchung',effort:'Mittel–Aufwendig'},
 {id:'cand-farmstay',name:'Farm Stay Packages',description:'Airbnb-Aufenthalte werden als Erlebnis-Pakete mit Tierkontakt, Frühstück, Picknick oder Workshop gebündelt.',status:'Kandidat',clusters:['Travel & Stay','Farm & Animals'],target:'Familien, Paare, Tier- und Naturfreunde',synergies:['Airbnb','Gnadenhof','Hofladen','Brunch-/Breakfast Boxes','Workshops'],resources:'Unterkunft, Buchungslogik, Erlebnisangebote',channels:'Paketbuchung',effort:'Mittel'},
 {id:'cand-microwedding',name:'Micro-Weddings / Elopement Packages',description:'Kleine Hochzeitspakete für wenige Gäste mit Location, Planung, Deko, Food, Dessert und optional Übernachtung.',status:'Kandidat',clusters:['Events & Weddings','Travel & Stay'],target:'Paare mit kleiner Hochzeit',synergies:['Hochzeitslocation','Eventplanning','Eventdeko-Verleih','Airbnb','Charcuterie To-go Stand','Dessert Catering / Dessert Table Service'],resources:'Location, Planung, Catering-/Dekoprozesse',channels:'Paketbuchung',effort:'Mittel'},
 {id:'cand-tiny-event',name:'Tiny Event Spaces',description:'Kleinere Räume oder Scheunenbereiche für Workshops, Baby Showers, JGAs, Geburtstage oder Firmengruppen.',status:'Kandidat',clusters:['Events & Weddings','Farm & Animals'],target:'Kleine private und geschäftliche Gruppen',synergies:['Hochzeitslocation','Workshops','Eventdeko-Verleih','Gnadenhof'],resources:'Nutzbarer Raum, Sanitär, Brandschutz/Genehmigungen',channels:'Stunden-/Tagesmiete',effort:'Aufwendig'},
 {id:'cand-popup',name:'Pop-up Stores',description:'Temporäre Verkaufsflächen für Desserts, Matchies, Journals, saisonale Produkte oder neue Konzepte.',status:'Kandidat',clusters:['Sales & Distribution','Products & Brands','Food & Desserts'],target:'Laufkundschaft, Eventbesucher',synergies:['Matchies','Journals & Planer','Cookies','Schokolade Bars / Balls / Donuts','Hofladen'],resources:'Mobiler Aufbau, Kasse, Warenbestand',channels:'Märkte, Events, Innenstadt-Pop-ups',effort:'Mittel'},
 {id:'cand-corporate-gifts',name:'Corporate Gift Boxes',description:'Geschenkboxen speziell für Unternehmen, Mitarbeitende, Kundengeschenke oder saisonale Anlässe.',status:'Kandidat',clusters:['Products & Brands'],target:'Unternehmen und Organisationen',synergies:['Matchies','Journals & Planer','Cookies','Schokolade Bars / Balls / Donuts'],resources:'B2B-Vertrieb, Verpackung, Personalisierung',channels:'Direktvertrieb B2B, Online',effort:'Mittel'},
 {id:'cand-corporate-events',name:'Corporate Event Packages',description:'Firmenveranstaltungen als Paket aus Location, Planung, Deko, Food, Workshops und optional kleinen Geschenken.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Unternehmen und Teams',synergies:['Eventplanning','Hochzeitslocation','Eventdeko-Verleih','Workshops','Food & Desserts'],resources:'B2B-Vertrieb, Eventkapazität, Planung',channels:'Direktvertrieb B2B',effort:'Mittel–Aufwendig'},
 {id:'cand-emergency-kit',name:'Event Emergency Kit / Bride Emergency Kit',description:'Kleine Notfallsets für Hochzeit oder JGA, z. B. mit Pflastern, Haarnadeln, Fleckenhilfe und weiteren Basics.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Brautpaare, JGAs, Eventgäste',synergies:['Matchies','Eventplanning','Hochzeitslocation'],resources:'Beschaffung, Verpackung, ggf. Personalisierung',channels:'Online, Location, Eventplanung',effort:'Einfach'},
 {id:'cand-wardrobe',name:'Rental Wardrobe / Event Accessories',description:'Verleih von Accessoires und ausgewählten Kleidungs-/Fotoprops für JGA, Shootings und Events.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'JGAs, Hochzeiten, Content-Shootings',synergies:['Matchies','Eventplanning','Wedding Content Creation'],resources:'Lager, Reinigung, Größen-/Bestandsverwaltung',channels:'Vermietung, Eventpakete',effort:'Mittel'},
 {id:'cand-signage',name:'Custom Signage',description:'Personalisierte Willkommensschilder, Sitzpläne, Tischnummern, Menükarten und Aufsteller.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Brautpaare, Veranstalter, Firmen',synergies:['Eventdeko-Verleih','Matchies','Eventplanning','Hochzeitslocation'],resources:'Design, Druck/Plotter bzw. Produktionspartner',channels:'Etsy/Online, Eventpakete',effort:'Einfach–Mittel'},
 {id:'cand-digital-wedding',name:'Digital Wedding Templates',description:'Digitale Einladungen, Sitzpläne, Menükarten, Checklisten und Planervorlagen zum Download.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Brautpaare und DIY-Hochzeiten',synergies:['Journals & Planer','Eventplanning','Matchies'],resources:'Designsoftware, Shop/Downloadsystem',channels:'Etsy/Online',effort:'Einfach'},
 {id:'cand-event-software',name:'Event Software / Planungstool',description:'Langfristig eigenes digitales Tool für Gäste, Budget, Aufgaben, Sitzplan und Dienstleisterkoordination.',status:'Kandidat',clusters:['Events & Weddings','Products & Brands'],target:'Brautpaare, Eventplaner, Veranstalter',synergies:['Eventplanning','Journals & Planer','Hochzeitslocation'],resources:'Softwareentwicklung, Hosting, Support',channels:'SaaS/Online',effort:'Sehr aufwendig'}
];
const defaultState={businesses:seedBusinesses,connections:seedConnections,candidates:seedCandidates,brainstorm:[],inspiration:[]};
let state=loadState();let currentPage='dashboard';
function loadState(){try{return JSON.parse(localStorage.getItem('businessEcoState'))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function mergeSeedUpdates(){state.businesses=state.businesses||[];state.connections=state.connections||[];state.candidates=state.candidates||[];const hb=seedBusinesses.find(b=>b.id==='hofladen');if(hb&&!state.businesses.some(b=>b.id==='hofladen'||b.name===hb.name))state.businesses.push(structuredClone(hb));seedConnections.filter(c=>['farm','hofladen','airbnb','automaten','matchies','cookies'].includes(c.from)||['hofladen'].includes(c.to)).forEach(c=>{if(!state.connections.some(x=>x.from===c.from&&x.to===c.to&&x.type===c.type))state.connections.push(structuredClone(c))});seedCandidates.forEach(c=>{if(!state.candidates.some(x=>x.id===c.id||x.name===c.name)&&!state.businesses.some(b=>b.name===c.name))state.candidates.push(structuredClone(c))});save()}
mergeSeedUpdates();
function save(){localStorage.setItem('businessEcoState',JSON.stringify(state))}
const pages=[['dashboard','Dashboard'],['businesses','Businesses'],['mindmap','Master Mindmap'],['synergies','Synergien'],['candidates','Kandidaten'],['inspiration','Inspiration'],['brainstorm','Brainstorming'],['implementation','Umsetzung'],['backup','Backup']];
const nav=document.getElementById('nav');
pages.forEach(([id,label])=>{const b=document.createElement('button');b.className='nav-btn';b.textContent=label;b.onclick=()=>renderPage(id);b.dataset.page=id;nav.appendChild(b)});
function renderPage(id){currentPage=id;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const titles={dashboard:['Dashboard','Dein gesamtes Business-Netzwerk auf einen Blick.'],businesses:['Businesses','Bestätigte Masterliste und Steckbriefe.'],mindmap:['Master Mindmap','Interaktive Karte aller bestätigten Businesses und Verbindungen.'],synergies:['Synergien','Cross-Selling, Kundenfluss und gemeinsame Ressourcen.'],candidates:['Kandidaten','Neue Ideen bleiben getrennt, bis du sie bestätigst.'],inspiration:['Inspiration','Bilder und Moodboard-Ideen mit Freigabestatus.'],brainstorm:['Brainstorming','Lose Gedanken, bevor daraus Kandidaten werden.'],implementation:['Umsetzung','Von der Idee bis zum aktiven Business.'],backup:['Backup','Daten exportieren, importieren oder zurücksetzen.']};document.getElementById('pageTitle').textContent=titles[id][0];document.getElementById('pageSubtitle').textContent=titles[id][1];document.getElementById('content').innerHTML='';({dashboard,businesses,mindmap,synergies,candidates,inspiration,brainstorm,implementation,backup}[id])()}
function section(html){document.getElementById('content').innerHTML=`<div class="section">${html}</div>`}
function dashboard(){const topConnections=[...state.businesses].map(b=>({b,n:state.connections.filter(c=>c.from===b.id||c.to===b.id).length})).sort((a,b)=>b.n-a.n).slice(0,5);section(`<div class="grid cards-4"><div class="metric"><small>Bestätigte Businesses</small><strong>${state.businesses.length}</strong></div><div class="metric"><small>Kandidaten</small><strong>${state.candidates.length}</strong></div><div class="metric"><small>Verbindungen</small><strong>${state.connections.length}</strong></div><div class="metric"><small>Cluster</small><strong>${Object.keys(CLUSTERS).length}</strong></div></div><div class="grid" style="grid-template-columns:1.3fr .7fr;margin-top:16px"><div class="panel"><div class="row space"><h3>Ökosystem Vorschau</h3><button class="secondary" onclick="renderPage('mindmap')">Mindmap öffnen</button></div><div class="image-placeholder" style="aspect-ratio:2/1">Interaktive Master-Mindmap mit ${state.businesses.length} Businesses</div></div><div class="panel"><h3>Stärkste Knoten</h3><div class="list">${topConnections.map(x=>`<div class="list-item"><span>${x.b.name}</span><span class="pill">${x.n} Verbindungen</span></div>`).join('')}</div></div></div>`)}
function businesses(){section(`<div class="toolbar"><input id="bizSearch" placeholder="Business suchen…"><select id="clusterFilter"><option value="">Alle Cluster</option>${Object.keys(CLUSTERS).map(c=>`<option>${c}</option>`).join('')}</select></div><div id="bizGrid" class="grid business-grid"></div>`);const paint=()=>{const q=document.getElementById('bizSearch').value.toLowerCase(),f=document.getElementById('clusterFilter').value;document.getElementById('bizGrid').innerHTML=state.businesses.filter(b=>(!q||b.name.toLowerCase().includes(q)||b.description.toLowerCase().includes(q))&&(!f||b.clusters.includes(f))).map(b=>`<div class="card business-card" onclick="openBusiness('${b.id}')"><div class="row space"><strong>${b.name}</strong><span class="status">${b.status}</span></div><div class="tags">${b.clusters.map(c=>`<span class="tag">${c}</span>`).join('')}</div><p class="muted">${b.description}</p><small>${state.connections.filter(c=>c.from===b.id||c.to===b.id).length} Verbindungen</small></div>`).join('')};paint();document.getElementById('bizSearch').oninput=paint;document.getElementById('clusterFilter').onchange=paint}
function openBusiness(id){const b=state.businesses.find(x=>x.id===id);const con=state.connections.filter(c=>c.from===id||c.to===id);section(`<button class="secondary" onclick="renderPage('businesses')">← Zurück</button><div class="detail" style="margin-top:14px"><div class="panel"><div class="row space"><div><h2>${b.name}</h2><div class="tags">${b.clusters.map(c=>`<span class="tag">${c}</span>`).join('')}</div></div><button class="secondary" onclick="editBusiness('${id}')">Bearbeiten</button></div><p>${b.description}</p><div class="kv"><strong>Status</strong><span>${b.status}</span><strong>Bestätigt</strong><span>Ja</span><strong>Notizen</strong><span>${b.notes||'—'}</span></div></div><div class="panel"><h3>Direkte Verbindungen</h3><div class="connections">${con.length?con.map(c=>{const other=state.businesses.find(x=>x.id===(c.from===id?c.to:c.from));return `<div class="connection"><strong>${other?.name||'Unbekannt'}</strong><br><span class="pill">${c.type}</span><p class="muted">${c.description}</p></div>`}).join(''):'<div class="empty">Noch keine Verbindung</div>'}</div></div></div><div class="panel" style="margin-top:16px"><h3>Inspiration</h3><div class="image-placeholder">Noch keine freigegebenen Bilder gespeichert</div></div>`);document.getElementById('pageTitle').textContent=b.name;document.getElementById('pageSubtitle').textContent='Business-Steckbrief und Netzwerk.'}
function mindmap(){section(`<div class="toolbar"><select id="edgeFilter"><option value="">Alle Verbindungstypen</option>${[...new Set(state.connections.map(c=>c.type))].map(t=>`<option>${t}</option>`).join('')}</select><button class="secondary" id="fitBtn">Ansicht zurücksetzen</button></div><div class="mindmap-wrap"><div id="mindCanvas" class="mindmap-canvas"></div></div>`);drawMindmap();document.getElementById('edgeFilter').onchange=drawMindmap}
function drawMindmap(){const canvas=document.getElementById('mindCanvas');if(!canvas)return;canvas.innerHTML='';const center={x:640,y:390};const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','edge-layer');svg.setAttribute('width','1500');svg.setAttribute('height','950');canvas.appendChild(svg);const clusterNames=Object.keys(CLUSTERS);const positions={};clusterNames.forEach((cl,ci)=>{const items=state.businesses.filter(b=>b.clusters.includes(cl));const angleBase=(Math.PI*2/clusterNames.length)*ci-Math.PI/2;const hubX=center.x+Math.cos(angleBase)*320,hubY=center.y+Math.sin(angleBase)*260;const label=document.createElement('div');label.className='cluster-label';label.style.left=(hubX-50)+'px';label.style.top=(hubY-65)+'px';label.textContent=cl;canvas.appendChild(label);items.forEach((b,i)=>{const spread=(i-(items.length-1)/2)*0.22;const angle=angleBase+spread;const radius=430+Math.min(100,Math.abs(i-(items.length-1)/2)*18);const x=center.x+Math.cos(angle)*radius,y=center.y+Math.sin(angle)*radius;positions[b.id]={x,y};const n=document.createElement('div');n.className='node';n.style.left=x+'px';n.style.top=y+'px';n.style.background=CLUSTERS[b.clusters[0]]||'#fff';n.innerHTML=`<strong>${b.name}</strong><div class="muted" style="font-size:11px;margin-top:4px">${b.clusters[0]}</div>`;n.onclick=()=>openBusiness(b.id);canvas.appendChild(n)})});const c=document.createElement('div');c.className='node center';c.style.left=center.x+'px';c.style.top=center.y+'px';c.innerHTML='MASTER<br>MINDMAP<div class="muted" style="font-size:11px;margin-top:6px">Business Ecosystem</div>';canvas.appendChild(c);const filter=document.getElementById('edgeFilter')?.value||'';state.connections.filter(e=>!filter||e.type===filter).forEach(e=>{const a=positions[e.from],b=positions[e.to];if(!a||!b)return;const line=document.createElementNS('http://www.w3.org/2000/svg','path');const ax=a.x+90,ay=a.y+35,bx=b.x+90,by=b.y+35;const mx=(ax+bx)/2,my=(ay+by)/2-30;line.setAttribute('d',`M ${ax} ${ay} Q ${mx} ${my} ${bx} ${by}`);line.setAttribute('class','edge');svg.appendChild(line)})}
function synergies(){const types=[...new Set(state.connections.map(c=>c.type))];section(`<div class="grid" style="grid-template-columns:.7fr 1.3fr"><div class="panel"><h3>Verbindungstypen</h3>${types.map(t=>`<div class="list-item"><span>${t}</span><span class="pill">${state.connections.filter(c=>c.type===t).length}</span></div>`).join('')}</div><div class="panel"><h3>Alle bestätigten Synergien</h3><div class="list">${state.connections.map(c=>{const a=state.businesses.find(b=>b.id===c.from)?.name,b=state.businesses.find(b=>b.id===c.to)?.name;return `<div class="list-item"><div><strong>${a} → ${b}</strong><div><span class="pill">${c.type}</span></div><small class="muted">${c.description}</small></div></div>`}).join('')}</div></div></div>`)}
function candidates(){section(`<div class="toolbar"><input id="candSearch" placeholder="Kandidat suchen…"><select id="candEffort"><option value="">Alle Aufwände</option><option>Einfach</option><option>Einfach–Mittel</option><option>Mittel</option><option>Mittel–Aufwendig</option><option>Aufwendig</option><option>Sehr aufwendig</option></select></div><div id="candGrid" class="grid business-grid"></div>`);const paint=()=>{const q=(document.getElementById('candSearch').value||'').toLowerCase(),e=document.getElementById('candEffort').value;document.getElementById('candGrid').innerHTML=state.candidates.filter(c=>(!q||[c.name,c.description,c.target,c.resources,c.channels,(c.synergies||[]).join(' ')].join(' ').toLowerCase().includes(q))&&(!e||c.effort===e)).map(c=>`<div class="card candidate"><div class="row space"><strong>${c.name}</strong><span class="pill">${c.status||'Kandidat'}</span></div><div class="tags">${(c.clusters||[]).map(x=>`<span class="tag">${x}</span>`).join('')}</div><p>${c.description||''}</p>${c.target?`<p><strong>Zielgruppe:</strong> ${c.target}</p>`:''}${c.synergies?.length?`<p><strong>Synergien:</strong> ${c.synergies.join(' · ')}</p>`:''}${c.resources?`<p><strong>Ressourcen:</strong> ${c.resources}</p>`:''}${c.channels?`<p><strong>Verkauf:</strong> ${c.channels}</p>`:''}${c.effort?`<p><strong>Aufwand:</strong> <span class="pill">${c.effort}</span></p>`:''}<div class="row"><button class="primary" onclick="approveCandidate('${c.id}')">Zur Masterliste</button><button class="danger" onclick="removeCandidate('${c.id}')">Verwerfen</button></div></div>`).join('')||'<div class="empty">Keine Kandidaten gefunden.</div>'};document.getElementById('candSearch').oninput=paint;document.getElementById('candEffort').onchange=paint;paint()}
function approveCandidate(id){const c=state.candidates.find(x=>x.id===id);if(!c)return;state.businesses.push({id:'biz'+Date.now(),name:c.name,description:c.description,clusters:c.clusters||[],status:'Idee',confirmed:true,notes:[c.target&&'Zielgruppe: '+c.target,c.synergies?.length&&'Synergien: '+c.synergies.join(' · '),c.resources&&'Ressourcen: '+c.resources,c.channels&&'Verkauf: '+c.channels,c.effort&&'Aufwand: '+c.effort].filter(Boolean).join('\n'),images:[]});state.candidates=state.candidates.filter(x=>x.id!==id);save();renderPage('candidates')}
function removeCandidate(id){state.candidates=state.candidates.filter(x=>x.id!==id);save();renderPage('candidates')}
function inspiration(){section(`<div class="panel"><div class="row space"><h3>Inspirationssammlung</h3><button class="secondary" onclick="addInspiration()">+ Inspiration</button></div>${state.inspiration.length?`<div class="grid business-grid">${state.inspiration.map(i=>`<div class="card"><div class="image-placeholder">${i.url?'Bild-Link gespeichert':'Moodboard'}</div><h4>${i.title}</h4><p class="muted">${i.business||'Allgemein'}</p><span class="pill">${i.status}</span></div>`).join('')}</div>`:'<div class="empty">Noch keine Bilder oder Moodboard-Ideen gespeichert.</div>'}</div>`)}
function brainstorm(){section(`<div class="panel"><div class="row space"><h3>Freies Brainstorming</h3><button class="secondary" onclick="addBrainstorm()">+ Gedanke</button></div><div class="list">${state.brainstorm.length?state.brainstorm.map(x=>`<div class="list-item"><div>${x.text}</div><button class="secondary" onclick="brainToCandidate('${x.id}')">→ Kandidat</button></div>`).join(''):'<div class="empty">Noch keine losen Gedanken gespeichert.</div>'}</div></div>`)}
function implementation(){const stages=['Idee','Recherche','Konzept','Businessplan','Test','Aufbau','Aktiv','Skalierung'];section(`<div class="grid business-grid">${stages.map(s=>`<div class="panel"><h3>${s}</h3>${state.businesses.filter(b=>b.status===s).map(b=>`<div class="list-item"><span>${b.name}</span><button class="secondary" onclick="advance('${b.id}')">Weiter</button></div>`).join('')||'<div class="muted">—</div>'}</div>`).join('')}</div>`)}
function advance(id){const stages=['Idee','Recherche','Konzept','Businessplan','Test','Aufbau','Aktiv','Skalierung'];const b=state.businesses.find(x=>x.id===id);const i=stages.indexOf(b.status);if(i<stages.length-1)b.status=stages[i+1];save();renderPage('implementation')}
function backup(){section(`<div class="grid" style="grid-template-columns:1fr 1fr"><div class="panel"><h3>Export</h3><p>Speichert alle Businesses, Verbindungen, Kandidaten, Inspirationen und Brainstorming-Daten.</p><button class="primary" onclick="exportData()">JSON exportieren</button></div><div class="panel"><h3>Import</h3><input type="file" id="importFile" accept="application/json"><button class="secondary" style="margin-top:10px" onclick="importData()">Importieren</button></div><div class="panel"><h3>Reset</h3><p>Setzt die PWA auf die mitgelieferten Startdaten zurück.</p><button class="danger" onclick="resetData()">Startdaten wiederherstellen</button></div></div>`)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='business-ecosystem-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const f=document.getElementById('importFile').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();renderPage('dashboard')}catch{alert('Ungültige JSON-Datei')}};r.readAsText(f)}
function resetData(){if(confirm('Wirklich auf Startdaten zurücksetzen?')){state=structuredClone(defaultState);save();renderPage('dashboard')}}
function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function addBusiness(){modal(`<h2>Neues bestätigtes Business</h2><div class="form-grid"><label>Name<input id="mName"></label><label>Status<select id="mStatus"><option>Idee</option><option>Recherche</option><option>Konzept</option></select></label><label class="wide">Beschreibung<textarea id="mDesc"></textarea></label><label class="wide">Cluster (mit Komma trennen)<input id="mClusters" placeholder="Food & Desserts, Events & Weddings"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveBusiness()">Speichern</button></div>`)}
function saveBusiness(){const name=mName.value.trim();if(!name)return;state.businesses.push({id:'biz'+Date.now(),name,description:mDesc.value.trim(),clusters:mClusters.value.split(',').map(x=>x.trim()).filter(Boolean),status:mStatus.value,confirmed:true,notes:'',images:[]});save();closeModal();renderPage('businesses')}
function editBusiness(id){const b=state.businesses.find(x=>x.id===id);modal(`<h2>${b.name} bearbeiten</h2><div class="form-grid"><label>Name<input id="eName" value="${esc(b.name)}"></label><label>Status<select id="eStatus">${['Idee','Recherche','Konzept','Businessplan','Test','Aufbau','Aktiv','Skalierung'].map(s=>`<option ${s===b.status?'selected':''}>${s}</option>`).join('')}</select></label><label class="wide">Beschreibung<textarea id="eDesc">${esc(b.description)}</textarea></label><label class="wide">Cluster<input id="eClusters" value="${esc(b.clusters.join(', '))}"></label><label class="wide">Notizen<textarea id="eNotes">${esc(b.notes||'')}</textarea></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveEdit('${id}')">Speichern</button></div>`)}
function saveEdit(id){const b=state.businesses.find(x=>x.id===id);b.name=eName.value;b.status=eStatus.value;b.description=eDesc.value;b.clusters=eClusters.value.split(',').map(x=>x.trim()).filter(Boolean);b.notes=eNotes.value;save();closeModal();openBusiness(id)}
function addCandidate(){modal(`<h2>Neuer Kandidat</h2><div class="form-grid"><label class="wide">Name<input id="cName"></label><label class="wide">Beschreibung<textarea id="cDesc"></textarea></label><label class="wide">Cluster<input id="cClusters"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveCandidate()">Speichern</button></div>`)}
function saveCandidate(){if(!cName.value.trim())return;state.candidates.push({id:'cand'+Date.now(),name:cName.value.trim(),description:cDesc.value.trim(),clusters:cClusters.value.split(',').map(x=>x.trim()).filter(Boolean),status:'Kandidat'});save();closeModal();renderPage('candidates')}
function addBrainstorm(){modal(`<h2>Brainstorming-Idee</h2><label>Gedanke<textarea id="bText"></textarea></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveBrainstorm()">Speichern</button></div>`)}
function saveBrainstorm(){if(!bText.value.trim())return;state.brainstorm.push({id:'brain'+Date.now(),text:bText.value.trim()});save();closeModal();renderPage('brainstorm')}
function brainToCandidate(id){const b=state.brainstorm.find(x=>x.id===id);state.candidates.push({id:'cand'+Date.now(),name:b.text.slice(0,60),description:b.text,clusters:[],status:'Kandidat'});state.brainstorm=state.brainstorm.filter(x=>x.id!==id);save();renderPage('brainstorm')}
function addInspiration(){modal(`<h2>Inspiration speichern</h2><div class="form-grid"><label>Titel<input id="iTitle"></label><label>Business<input id="iBusiness"></label><label class="wide">Bild-URL / Hinweis<input id="iUrl"></label><label>Status<select id="iStatus"><option>Nicht geprüft</option><option>Bestätigt</option><option>Abgelehnt</option></select></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveInspiration()">Speichern</button></div>`)}
function saveInspiration(){if(!iTitle.value.trim())return;state.inspiration.push({id:'img'+Date.now(),title:iTitle.value.trim(),business:iBusiness.value.trim(),url:iUrl.value.trim(),status:iStatus.value});save();closeModal();renderPage('inspiration')}
function esc(s){return (s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
document.getElementById('addBusinessBtn').onclick=addBusiness;document.getElementById('addCandidateBtn').onclick=addCandidate;document.getElementById('exportQuick').onclick=exportData;
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderPage('dashboard');
